{
    "name": "Steel Sheet Configurator",
    "summary": "Laser Cutter Sheet Configuration Module",
    "author": "Niels Göttsch",
    "website": "https://www.ife.de",
    "category": "Manufacturing",
    "version": "18.0.1.0.0",
    "depends": ["web"],
    "data": [
        "security/ir.model.access.csv",
        "views/ife_customer_project_views.xml",
        "views/ife_environment_views.xml",
        "views/repo_views.xml",
        "views/repo_branch_views.xml",
        "views/environment_folder_views.xml",
        "views/repo_module_views.xml",
        "views/environment_module_views.xml",
        "views/ife_deployer_menu.xml",
    ],
    "license": "LGPL-3",
    "application": True,
}
